### ISSUE TITLE
Remove mips64el-linux-android

### ISSUE THREAD

**Issue by tir38** [k3b/intent-intercept#10]
I'm trying to build this locally. I'm gettin this error:

```
* What went wrong:
A problem occurred configuring project ':app'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
```

Seems this ABI was deprecated:
https://issuetracker.google.com/issues/112779429
https://developer.android.com/ndk/guides/abis#sa

**Comment by k3b** [comment]
are you shure that this ticket is added to the correct project?

as far as i know intent-intercept  does not use any native code .

**Comment by tir38** [comment]
Good point. It could be from one of your dependencies. Not sure though.
