### ISSUE TITLE
App is stuck on a screen in settings / Unclear how to use the app

### ISSUE THREAD

**Issue by skompc** [k3b/intent-intercept#24]
I just downloaded the app and when I launch I ca t seem to leave this screen
![Screenshot_20220814-151750_Intent Intercept](https://user-images.githubusercontent.com/5279725/184553467-eb0c8f3e-f3ba-4911-9251-db03e548fedb.jpg)

**Comment by k3b** [comment]
which android version do you have  on your device?

what happens when you press "send test intent"?

the back arrow "<" does not work?

**Comment by rocket-pig** [comment]
Exact same problem. Android 11. Any other info I can provide to help?

Edit: never mind, how to use the app was not immediately clear. I get it now. I had assumed he would work like a traffic monitor...Android probably doesn't allow such freedom. You send a test intent to the app itself, and then can edit it. Got it.

**Comment by skompc** [comment]
> Exact same problem. Android 11. Any other info I can provide to help?
> 
> Edit: never mind, how to use the app was not immediately clear. I get it now. I had assumed he would work like a traffic monitor...Android probably doesn't allow such freedom. You send a test intent to the app itself, and then can edit it. Got it.

Oh that's how it works?... so not like packet capture but for internal intents?

**Comment by rocket-pig** [comment]
It becomes part of your "Share to" menu and you can send intents from other apps as well. Hopefully this helps the next fella.

**Comment by k3b** [comment]
@skompc @rocket-pig Sorry for Missunderstanding. As a ["Fachidiot"](https://english.stackexchange.com/questions/327748/is-there-really-no-english-equivalent-to-germans-fachidiot) or "narrow-minded-spezialist and nerd" I was not aware that it is not clear how the app works.

I have to update the app description with an example "how to use the app" ;-)

**Comment by rocket-pig** [comment]
It's brilliant and much appreciated. An intro would probably be great too! Thanks again for free app that let us explore.

Sep 1, 2022 12:24:15 AM k3b ***@***.***>:

**Comment by k3b** [comment]
done: updated README.md
