### ISSUE TITLE
Wont Intercept android.intent.action.OPEN_DOCUMENT_TREE (will be closed on 2024-03-13)

### ISSUE THREAD

**Issue by cbellosoto** [k3b/intent-intercept#29]
Trying to intercept intent:#Intent;action=android.intent.action.OPEN_DOCUMENT_TREE;B.android.content.extra.SHOW_ADVANCED=true;S.android.provider.extra.PROMPT=Allow%20Write%20Permission;B.android.intent.extra.LOCAL_ONLY=false;end 
 But it is not triggering the app

**Comment by cbellosoto** [comment]
The Files app opens without the intercept. Disableling the Files apps allows for the intercept but then there is no files app available to send the intent to.

**Comment by k3b** [comment]
@cbellosoto cbellosoto

Thanks for reporting.

> But it is not triggering the app

I assume that "Always use &lt;&lt;NameOfYourDefaultFilemanager>>" is enabled.

You can use [Material Files](https://f-droid.org/en/packages/me.zhanghai.android.files/) as alternative Filemanager that also supports "OPEN_DOCUMENT_TREE"

Which android version are you using?

**Comment by k3b** [comment]
@cbellosoto does this issue still exist? If i donot get an answer till 2024-03-13 i will close this issue
