### ISSUE TITLE
Get the code of the test intents  (will be closed on 2024-03-13)

### ISSUE THREAD

**Issue by Libaninourab** [k3b/intent-intercept#31]
The app Intent Intercept sends successfully a Test Intent to an installed app called Thermer(for printing) i need to get the structure of this uri intent to use it.
How can I get it

**Comment by k3b** [comment]
The content of "URI" is produced by [Intent#toUri(Intent.URI_INTENT_SCHEME)](https://developer.android.com/reference/android/content/Intent#toUri(int))

called in https://github.com/k3b/intent-intercept/blob/0b42ad69f405213fbef9b3c626f278f6aafd9e7d/app/src/main/java/uk/co/ashtonbrsc/intentexplode/Explode.java#L871C34-L871C41

you can use [Uri#parse(java.lang.String)](https://developer.android.com/reference/android/net/Uri#parse(java.lang.String)) to convert the string back to an intent

If this answer solves your problem please close this issue

**Comment by k3b** [comment]
@Libaninourab is your issue solved? if there is no reaction form you till march 13th i will close this issue.
