### ISSUE TITLE
GUI error

### ISSUE THREAD

**Issue by iddq** [k3b/intent-intercept#33]
That's all I can see from the app, no menus etc.

![intent](https://github.com/user-attachments/assets/40e65ffa-d775-41bd-a27c-f7812faafea5)

**Comment by k3b** [comment]
Your screenshot shows the settings page.

Press "Send Test Intend" and select "Intent intercept" to see "Intent intercept" in action.

For more info see https://github.com/k3b/intent-intercept/blob/master/README.md#example-usage-of-intentintercept.
