### ISSUE TITLE
It doesn't intercept the intents for playing video in an external player by NewPipe

### ISSUE THREAD

**Issue by KOLANICH** [k3b/intent-intercept#5]
I use [org.schabi.newpipe](https://github.com/TeamNewPipe/NewPipe).

**Comment by k3b** [comment]
In the debugger can you put a breakpoint to https://github.com/TeamNewPipe/NewPipe/blob/61472a995f76468b1cffe168d5e75de8c2b06224/app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java line 212 and give me the intent data used to start the player?

* action=ACTION_VIEW
* data=???Uri.parse(stream.getUrl())??
* mime=???stream.getFormat().getMimeType()???

	    // NavigationHelper.java line 212
	    public static void playOnExternalPlayer(Context context, String name, String artist, Stream stream) {
		Intent intent = new Intent();
		intent.setAction(Intent.ACTION_VIEW);
		intent.setDataAndType(Uri.parse(stream.getUrl()), stream.getFormat().getMimeType());
		intent.putExtra(Intent.EXTRA_TITLE, name);
		intent.putExtra("title", name);
		intent.putExtra("artist", artist);
		intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
		
		resolveActivityOrAskToInstall(context, intent);
	    }

**Comment by KOLANICH** [comment]
No, I don't have any Android devtools on my PC anymore. Also I don't seriously need that anymore.  If I need that again, I will reopen the issue.
