### ISSUE TITLE
android.telecom.InCallService / Dialer

### ISSUE THREAD

**Issue by bdbais** [k3b/intent-intercept#8]
Is it possible to intercept the default dialer indent anche change a text box inside (like caller name or phone number) for privacy enhancement?

**Comment by k3b** [comment]
I donot know, if it is possible. Currently intent-intercept only intercepts Activity resolution. This looks like you need to implement and register a service before beeing allowed to intercept.....

From https://developer.android.com/reference/android/telecom/InCallService we need to intercept

* action=android.intent.action.DIAL

which seems to possible only if you register a service for

* action=android.telecom.InCallService

but i donot know if this will work. Can you do and test it?
