### ISSUE TITLE
Licence spelled license

### ISSUE THREAD

**Issue by jmikedupont2** [k3b/intent-intercept#9]
Chexk the spelling

**Comment by TPS** [comment]
@jmikedupont2 You may not realize either or both are correct, depending.…  See details @, e.g., https://www.grammarly.com/blog/licence-license/

**Comment by jmikedupont2** [comment]
Either but not both at the same time. On the screen it shows both.

**Comment by TPS** [comment]
No, that's probably right: @k3b uses a licence (what s/he _calls_ it) called Apache License (what Apache _named_ it), Version 2.0

**Comment by jmikedupont2** [comment]
Ok if that is what you want.

**Comment by k3b** [comment]
TODO for me (as a non native english speaker)

* rename all licence to License in docs and source code
